"""empty message

Revision ID: 19d95e0fee74
Revises: 
Create Date: 2018-12-22 21:29:01.099488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19d95e0fee74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suppliers')
    op.add_column('user', sa.Column('name', sa.String(length=128), nullable=True))
    op.drop_constraint('user_supplierName_key', 'user', type_='unique')
    op.drop_column('user', 'supplierName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('supplierName', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.create_unique_constraint('user_supplierName_key', 'user', ['supplierName'])
    op.drop_column('user', 'name')
    op.create_table('suppliers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('supplierName', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='suppliers_pkey'),
    sa.UniqueConstraint('supplierName', name='suppliers_supplierName_key')
    )
    # ### end Alembic commands ###
