"""empty message

Revision ID: ab14c5191297
Revises: f1f8ca6c3126
Create Date: 2018-12-22 21:38:45.708149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab14c5191297'
down_revision = 'f1f8ca6c3126'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplierName', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itemName', sa.String(length=128), nullable=True),
    sa.Column('itemCode', sa.String(length=128), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('suppliers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('supplierName', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='suppliers_pkey')
    )
    op.drop_table('supplier_item')
    op.drop_table('supplier')
    # ### end Alembic commands ###
